[build]
  command = "nx build auth && nx build fincare"
  publish = "dist/apps/fincare"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
